# nombre del ejecutable
TARGET = scrabble

# compilador
CXX = g++

# Flags del compilador
CXXFLAGS = -Wall _Wextra -std=c++17 -02 -Iinclude

# directorios
SRC_DIR = src
INC_DIR = include


# encontrar archivos fuente dentro de "src" y agregar "main.cpp"
SRC = $(shell find $(SRC_DIR) -type f -name "*.cpp") main.cpp

# archivos objeto (.cpp -> .o)
OBJ = $(SRC:.cpp=.o)

# regla principal
$(TARGET): $(OBJ)
    $(CXX) $(CXXFLAGS) -o $@ $^

# regla para compilar archivos .cpp a .o
%.o %.cpp
    $(CXX) $(CXXFLAGS) -c $< -o $@

# limpiar archivos compilados
clean:
    rm -f $(OBJ) $(TARGET)

# forzar recompilacion
rebuild: clean $(TARGET)


# makefile -> sin extension.
# para compilar ->  make
# para limpiar archivos compilados ->   make clean
# para recompilar todo -> make rebuild
